### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by aha1215** [ahernandez1215/Group6_CST438_Project3_Backend#30]

**Comment by rltsystems** [comment]
This is a front-end story, and will be worked on via replit, but current assignee will be @jbarrosoarr 
The replit link is here: [REPLIT Link](https://replit.com/@RyanTrinh3/Group6CST438Project03Web)

**Comment by rltsystems** [comment]
Front-end template for landing page finished linked on Pull Request: https://github.com/rltsystems/Group6_CST438_Project03_Web/pull/21
